name: windows

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: install conan
      run : choco install conan
    - name: build
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        SET PATH=%PATH%;c:\Program Files\Conan
        cmake .. -G "Visual Studio 16 2019" -A x64
        cmake --build .
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: build