name: windows

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: install conan
      run : pip install conan
    - name: install submodules
      run: git submodule update --init --recursive
    - name: build
      run: |
        $env:PATH += ';C:\Program Files\Conan\conan'
        ($env:Path).Replace(';',"`n")
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A x64
        cmake --build .
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: build